prSkipCI: true
copyIssueDescriptionToPR: true
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true
openDraftPR: true
commentMessage: "✅ Work Branch Created!\n```git checkout ${branchName}```\ncopy this 👆"
