branchName: '${issue.title,}--issue-${issue.number}^'
mode: auto
defaultBranch: 'master'
openPR: true
copyIssueLabelsToPR: true
branches:
  - label: question
    skip: true
  - label: '*'
    name: master
