mode: immediate
openPR: false
prSkipCI: true
copyIssueDescriptionToPR: true
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true
commentMessage: "✅ Work Branch Created!\n```git checkout ${branchName}```\ncopy this 👆"
